PROMPT:
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feat"
        DESC: "New feature"
      - VALUE: "fix"
        DESC: "Bug fix"
      - VALUE: "test"
        DESC: "No production code change"
      - VALUE: "style"
        DESC: "No logic code change"
      - VALUE: "build-ci"
        DESC: "Changes on the build system or CI files"
      - VALUE: "refactor"
        DESC: "Refactoring production code"
      - VALUE: "docs"
        DESC: "Changes to documentation"
      - VALUE: "chore"
        DESC: "No production code change"
  - KEY: "MODULE"
    LABEL: "Affected module"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
  - KEY: "LABEL"
    LABEL: "Adding label to commit"
    OPTIONS:
      - VALUE: ""
        DESC: "None"
      - VALUE: "[WIP]"
        DESC: "Work in progress"
      - VALUE: "[CI-SKIP]"
        DESC: "Skip ci pipeline"
TEMPLATE: "{{CHANGE}}({{MODULE}}): {{MESSAGE}} {{LABEL}}"
